version: "3.8"

x-laravel:
    &laravel
    restart: unless-stopped
    build:
        context: .
        dockerfile: ./docker/laravel/Dockerfile
        args:
            WWWGROUP: "${WWWGROUP:-1000}"
    environment:
        WWWUSER: "${WWWUSER:-1000}"
        LARAVEL_SAIL: 1
    volumes:
        - ".:/var/www/html"
    ports:
        - "${APP_PORT:-9000}:9000"
    extra_hosts:
        - "host.docker.internal:host-gateway"

services:
    nginx:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
            args:
                - NGINX_CONF_FILE=${NGINX_CONF:-./docker/nginx/laravel.conf}
        volumes:
            - ./public:/var/www/html/public
            - ./docker/nginx/laravel.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "${APP_PORT:-80}:80"
        depends_on:
            - laravel
        extra_hosts:
            - "host.docker.internal:host-gateway"
    laravel:
        <<: *laravel
        expose:
            - 9000

    db:
        image: "postgres:14"
        environment:
            PGPASSWORD: "${DB_PASSWORD:-secret}"
            POSTGRES_DB: "${DB_DATABASE}"
            POSTGRES_USER: "${DB_USERNAME}"
            POSTGRES_PASSWORD: "${DB_PASSWORD:-secret}"
        ports:
            - "${FORWARD_DB_PORT:-5432}:5432"
        volumes:
            - "sail-pgsql:/var/lib/postgresql/data"
        healthcheck:
            test:
                [
                    "CMD",
                    "pg_isready",
                    "-q",
                    "-d",
                    "${DB_DATABASE}",
                    "-U",
                    "${DB_USERNAME}"
                ]
            retries: 3
            timeout: 5s
volumes:
    sail-pgsql:
        driver: local
